baud_rate: 9600
com_port: /dev/ttyACM0
invert_sliders: false
noise_reduction: default
slider_mapping:
  0:
  - kitty
  1:
  - wine64-preloader
  2:
  - zen-bin
  3:
  - chromium
  4:
  - chrome
  - firefox
  - spotify
